/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/admin/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Service Settings
         * @description Expose non-sensitive runtime configuration (administrators only).
         *
         *     The response is built field by field from an allow-list rather than dumping
         *     the whole settings object, so security-critical values can never leak: the
         *     JWT signing secret (``secret_key``) is omitted entirely, and every
         *     connection string is reduced to its backend/scheme via :func:`_scheme`.
         */
        get: operations["get_service_settings_api_admin_settings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Users
         * @description List all registered users, newest first (administrators only).
         */
        get: operations["list_users_api_admin_users_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users/quota": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update All Quotas
         * @description Set every user's storage quota to the same value (0 = unlimited).
         *
         *     Overwrites any per-user quotas. It does not change the default applied to
         *     future accounts, which comes from ``EASYSHARE_STORAGE_QUOTA_PER_USER``.
         *
         *     Registered before ``/{user_id}`` so the literal ``quota`` segment is not
         *     captured as a (non-integer) user id.
         */
        patch: operations["update_all_quotas_api_admin_users_quota_patch"];
        trace?: never;
    };
    "/api/admin/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete User
         * @description Delete a user and all of their packages, files and shares.
         *
         *     Administrators cannot delete their own account, so an instance always
         *     keeps at least one administrator.
         */
        delete: operations["delete_user_api_admin_users__user_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update User
         * @description Update a user's profile, active state, admin rights or storage quota.
         *
         *     Administrators cannot revoke their own admin rights or deactivate their own
         *     account, so an instance always keeps at least one active administrator.
         */
        patch: operations["update_user_api_admin_users__user_id__patch"];
        trace?: never;
    };
    "/api/admin/users/{user_id}/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reset User Password
         * @description Set a new password for a user (administrators only).
         *
         *     Intended for account recovery. The new password is hashed with Argon2id and
         *     is never logged or echoed back. For an immediate lockout of a compromised
         *     account, deactivate it (the account's tokens then stop working at once).
         */
        post: operations["reset_user_password_api_admin_users__user_id__password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * All Activity
         * @description The full audit log (administrators only).
         */
        get: operations["all_activity_api_audit_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audit/mine": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * My Activity
         * @description Audit events for packages/shares owned by the current user.
         */
        get: operations["my_activity_api_audit_mine_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Auth Config
         * @description Public auth-related feature flags for the frontend.
         */
        get: operations["auth_config_api_auth_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Authenticate with username/email and password, returning a JWT.
         */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Me
         * @description Return the currently authenticated user.
         */
        get: operations["read_me_api_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Change My Password
         * @description Change the authenticated user's password.
         *
         *     The current password must be supplied and verified before the change is
         *     applied, so an unattended, already-authenticated session cannot silently
         *     set a new password. Access tokens are stateless and remain valid until they
         *     expire; deactivating an account is the tool for an immediate lockout.
         */
        post: operations["change_my_password_api_auth_me_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me/usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read My Usage
         * @description Return the signed-in user's storage consumption and quota.
         *
         *     Kept separate from ``/auth/me`` (which the SPA polls on every navigation)
         *     so the usage aggregate is only computed on the screens that display it.
         */
        get: operations["read_my_usage_api_auth_me_usage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register
         * @description Register a new user account.
         */
        post: operations["register_api_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Simple liveness probe: process is up. Does not check dependencies.
         */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/packages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Packages
         * @description List packages owned by the current user, newest first (paginated).
         *
         *     Each item carries a ``file_count`` computed by a single grouped query rather
         *     than the full file list, so listing N packages never serialises every file
         *     of every package (avoids N+1 and large payloads). ``total`` lets the client
         *     render page controls without fetching every package. An optional ``q``
         *     filters by a case-insensitive substring of the package name or description.
         */
        get: operations["list_packages_api_packages_get"];
        put?: never;
        /**
         * Create Package
         * @description Create a new (empty) package owned by the current user.
         */
        post: operations["create_package_api_packages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/packages/{package_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Package
         * @description Retrieve a single owned package.
         */
        get: operations["get_package_api_packages__package_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Package
         * @description Delete a package and all of its stored files.
         */
        delete: operations["delete_package_api_packages__package_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Package
         * @description Update package name or description.
         */
        patch: operations["update_package_api_packages__package_id__patch"];
        trace?: never;
    };
    "/api/packages/{package_id}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download All Files
         * @description Download a package as a zip archive.
         *
         *     Owners may pass ``file_ids`` repeatedly to archive a specific subset;
         *     omitting it includes every file in the package.
         */
        get: operations["download_all_files_api_packages__package_id__download_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/packages/{package_id}/download-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Package Download Token
         * @description Issue a short-lived token to download this package via a plain navigation.
         *
         *     The SPA fetches a token, then points the browser at the download URL with
         *     the token in the query string, so files/archives stream to disk instead of
         *     being buffered in memory behind an Authorization header.
         */
        post: operations["create_package_download_token_api_packages__package_id__download_token_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/packages/{package_id}/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload File
         * @description Upload a file into a package.
         */
        post: operations["upload_file_api_packages__package_id__files_post"];
        /**
         * Delete All Files
         * @description Delete files from a package, keeping the package itself.
         *
         *     Owners may pass ``file_ids`` repeatedly to delete a specific subset;
         *     omitting it deletes every file in the package.
         */
        delete: operations["delete_all_files_api_packages__package_id__files_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/packages/{package_id}/files/{file_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete File
         * @description Delete a single file from a package.
         */
        delete: operations["delete_file_api_packages__package_id__files__file_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/packages/{package_id}/files/{file_id}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download Owned File
         * @description Download a single file from an owned package.
         */
        get: operations["download_owned_file_api_packages__package_id__files__file_id__download_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/packages/{package_id}/share": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Share
         * @description Get the current share configuration for a package.
         */
        get: operations["get_share_api_packages__package_id__share_get"];
        put?: never;
        /**
         * Enable Share
         * @description Enable sharing for a package, generating a valid share id (token).
         */
        post: operations["enable_share_api_packages__package_id__share_post"];
        /**
         * Disable Share
         * @description Disable sharing and remove the share link for a package.
         */
        delete: operations["disable_share_api_packages__package_id__share_delete"];
        options?: never;
        head?: never;
        /**
         * Update Share
         * @description Update visibility, enabled state or allowed emails.
         */
        patch: operations["update_share_api_packages__package_id__share_patch"];
        trace?: never;
    };
    "/api/packages/{package_id}/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Package Stats
         * @description Aggregate share view/download counters for an owned package.
         *
         *     Views are read from the share's denormalised ``view_count``; download totals
         *     (and the most recent download time) come from a single grouped query over
         *     the audit log. Per-file download counts are read straight from each file's
         *     denormalised ``download_count`` column (kept current on every share
         *     download), so the endpoint no longer scans and JSON-parses every download
         *     event. View and per-file download counters are accumulated in memory and
         *     flushed to the database in batches, so the still-buffered delta is added
         *     here to keep the numbers the owner sees near-real-time.
         */
        get: operations["get_package_stats_api_packages__package_id__stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/packages/{package_id}/uploads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Upload
         * @description Open a resumable upload, validating the declared size against the caps.
         */
        post: operations["create_upload_api_packages__package_id__uploads_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/packages/{package_id}/uploads/{upload_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Upload
         * @description Return the current offset so a client can resume an interrupted upload.
         *
         *     Reconciles ``received`` with the scratch file's actual length in case a
         *     crash lost the last offset update, so the client is never told to resume
         *     past what is truly on disk.
         */
        get: operations["get_upload_api_packages__package_id__uploads__upload_id__get"];
        put?: never;
        post?: never;
        /**
         * Abort Upload
         * @description Abort an in-progress upload, discarding its scratch file.
         */
        delete: operations["abort_upload_api_packages__package_id__uploads__upload_id__delete"];
        options?: never;
        head?: never;
        /**
         * Upload Chunk
         * @description Append one chunk at ``Upload-Offset``; finalize when the file is complete.
         *
         *     The offset must equal the session's current received length (so a retried or
         *     out-of-order chunk cannot corrupt the file), and the chunk must not push the
         *     total past the declared size. On the final chunk the assembled file is moved
         *     into storage and its ``PackageFile`` is returned with ``complete: true``.
         */
        patch: operations["upload_chunk_api_packages__package_id__uploads__upload_id__patch"];
        trace?: never;
    };
    "/api/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ready
         * @description Readiness probe: the app can actually serve traffic (DB + storage).
         */
        get: operations["ready_api_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/s/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * View Share
         * @description View share metadata. Files are hidden for restricted shares.
         *
         *     Each view bumps a denormalised counter on the share rather than writing an
         *     audit row, so a heavily crawled or refreshed public link cannot amplify into
         *     unbounded audit-table writes. The increment is buffered in process memory
         *     and flushed in coalesced batches by a background task, so a viral link does
         *     not serialise a per-hit ``UPDATE`` + commit on the single share row. The
         *     endpoint is also rate-limited.
         */
        get: operations["view_share_api_s__token__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/s/{token}/access": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Access Share
         * @description Unlock a restricted share by providing an allowed email address.
         *
         *     When email verification is enabled, this only *starts* the flow: a one-time
         *     code is emailed and the response asks the recipient to confirm it via
         *     ``/verify`` (files stay hidden). To avoid revealing whether an address is
         *     allow-listed, the response is identical whether or not the email is allowed;
         *     a code is only actually sent to an allow-listed address. When email is not
         *     configured the historical behaviour applies: knowing an allowed email grants
         *     access immediately.
         */
        post: operations["access_share_api_s__token__access_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/s/{token}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download Shared Archive
         * @description Download all files, or a selected subset, as a zip archive.
         *
         *     Recipients may pass ``file_ids`` repeatedly to select specific files;
         *     when omitted, every file in the package is included. The archive is streamed
         *     incrementally, so it is never buffered in full, and the per-file download
         *     count is bumped only once the archive has finished streaming (a client that
         *     disconnects part-way is not counted).
         */
        get: operations["download_shared_archive_api_s__token__download_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/s/{token}/files/{file_id}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download Shared File
         * @description Download a single file from a share.
         */
        get: operations["download_shared_file_api_s__token__files__file_id__download_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/s/{token}/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Verify Share
         * @description Confirm the emailed one-time code and unlock a restricted share.
         *
         *     The email must still be on the allow-list (so removing an address revokes a
         *     pending code) and the code must be correct, unexpired and within the attempt
         *     budget. Success returns the same short-lived download token as the
         *     no-verification path.
         */
        post: operations["verify_share_api_s__token__verify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AdminUserRead
         * @description User view for administrators, augmented with current storage usage.
         */
        AdminUserRead: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Id */
            id: number;
            /** Is Active */
            is_active: boolean;
            /** Is Admin */
            is_admin: boolean;
            /** Storage Quota */
            storage_quota: number;
            /**
             * Storage Used
             * @default 0
             */
            storage_used: number;
            /** Username */
            username: string;
        };
        /** AuditEventRead */
        AuditEventRead: {
            /** Action */
            action: string;
            /** Actor */
            actor: string | null;
            /** Client Ip */
            client_ip: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Detail */
            detail?: {
                [key: string]: unknown;
            } | null;
            /** Id */
            id: number;
            /** Package Id */
            package_id: number | null;
            /** Request Id */
            request_id: string | null;
            /** Target */
            target: string | null;
        };
        /** AuditPage */
        AuditPage: {
            /** Items */
            items: components["schemas"]["AuditEventRead"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Retention Days */
            retention_days: number;
            /** Total */
            total: number;
        };
        /** AuthConfig */
        AuthConfig: {
            /** Allow Registration */
            allow_registration: boolean;
            /**
             * Chunk Size
             * @default 8388608
             */
            chunk_size: number;
            /**
             * Chunk Uploads Enabled
             * @default true
             */
            chunk_uploads_enabled: boolean;
            /** Email Verification Enabled */
            email_verification_enabled: boolean;
            /** Max File Size */
            max_file_size: number;
            /** Max Files Per Package */
            max_files_per_package: number;
        };
        /** Body_login_api_auth_login_post */
        Body_login_api_auth_login_post: {
            /** Client Id */
            client_id?: string | null;
            /**
             * Client Secret
             * Format: password
             */
            client_secret?: string | null;
            /** Grant Type */
            grant_type?: string | null;
            /**
             * Password
             * Format: password
             */
            password: string;
            /**
             * Scope
             * @default
             */
            scope: string;
            /** Username */
            username: string;
        };
        /** Body_upload_file_api_packages__package_id__files_post */
        Body_upload_file_api_packages__package_id__files_post: {
            /** File */
            file: string;
        };
        /**
         * BulkQuotaResult
         * @description How many user rows a bulk quota update affected.
         */
        BulkQuotaResult: {
            /** Updated */
            updated: number;
        };
        /**
         * BulkQuotaUpdate
         * @description Set the same storage quota (bytes; 0 = unlimited) for every user.
         */
        BulkQuotaUpdate: {
            /** Storage Quota */
            storage_quota: number;
        };
        /**
         * DownloadToken
         * @description Short-lived token authorising a browser to stream an owner download.
         */
        DownloadToken: {
            /** Token */
            token: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** MessageResponse */
        MessageResponse: {
            /** Detail */
            detail: string;
        };
        /** PackageCreate */
        PackageCreate: {
            /** Description */
            description?: string | null;
            /** Name */
            name: string;
        };
        /** PackageFileRead */
        PackageFileRead: {
            /** Content Type */
            content_type: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Filename */
            filename: string;
            /** Id */
            id: number;
            /** Size */
            size: number;
        };
        /**
         * PackageListItem
         * @description A package as shown in the paginated list: metadata plus a file count.
         *
         *     The full ``files`` array is intentionally omitted so listing N packages does
         *     not serialise every file of every package (the dashboard only needs the
         *     count); fetch a single package to get its files.
         */
        PackageListItem: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Description */
            description: string | null;
            /**
             * File Count
             * @default 0
             */
            file_count: number;
            /** Id */
            id: number;
            /** Name */
            name: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * PackagePage
         * @description A paginated page of the current user's packages.
         */
        PackagePage: {
            /** Items */
            items: components["schemas"]["PackageListItem"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /** PackageRead */
        PackageRead: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Description */
            description: string | null;
            /**
             * Files
             * @default []
             */
            files: components["schemas"]["PackageFileRead"][];
            /** Id */
            id: number;
            /** Name */
            name: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * PackageStats
         * @description Aggregated share view/download counters for an owned package.
         */
        PackageStats: {
            /** Downloads */
            downloads: number;
            /** File Downloads */
            file_downloads?: {
                [key: string]: number;
            };
            /** Last Downloaded At */
            last_downloaded_at?: string | null;
            /** Views */
            views: number;
        };
        /** PackageUpdate */
        PackageUpdate: {
            /** Description */
            description?: string | null;
            /** Name */
            name?: string | null;
        };
        /**
         * PasswordChange
         * @description Self-service password change; the current password must be provided.
         */
        PasswordChange: {
            /** Current Password */
            current_password: string;
            /** New Password */
            new_password: string;
        };
        /**
         * PasswordReset
         * @description Administrator-initiated password reset for another user.
         */
        PasswordReset: {
            /** New Password */
            new_password: string;
        };
        /** PublicFile */
        PublicFile: {
            /** Content Type */
            content_type: string;
            /** Filename */
            filename: string;
            /** Id */
            id: number;
            /** Size */
            size: number;
        };
        /** PublicShareRead */
        PublicShareRead: {
            /** Download Token */
            download_token?: string | null;
            /** Files */
            files: components["schemas"]["PublicFile"][];
            /** Package Description */
            package_description: string | null;
            /** Package Name */
            package_name: string;
            /** Requires Email */
            requires_email: boolean;
            /** Token */
            token: string;
            /**
             * Verification Required
             * @default false
             */
            verification_required: boolean;
            visibility: components["schemas"]["ShareVisibility"];
        };
        /**
         * ServiceSettingsRead
         * @description Non-sensitive runtime configuration for the admin settings view.
         *
         *     Assembled from an explicit allow-list in the route: the JWT signing secret
         *     is never included, and connection strings (database, rate-limit store,
         *     object storage) are reduced to their backend/scheme so no host or embedded
         *     credential can leak.
         */
        ServiceSettingsRead: {
            /** Access Token Expire Minutes */
            access_token_expire_minutes: number;
            /** Algorithm */
            algorithm: string;
            /** Allow Registration */
            allow_registration: boolean;
            /** App Name */
            app_name: string;
            /** Audit Prune Interval Hours */
            audit_prune_interval_hours: number;
            /** Audit Retention Days */
            audit_retention_days: number;
            /** Cors Origins */
            cors_origins: string[];
            /** Database Backend */
            database_backend: string;
            /** Db Max Overflow */
            db_max_overflow: number;
            /** Db Pool Size */
            db_pool_size: number;
            /** Db Pool Timeout */
            db_pool_timeout: number;
            /** Deployment Profile */
            deployment_profile: string;
            /** Email Verification Enabled */
            email_verification_enabled: boolean;
            /** Environment */
            environment: string;
            /** Log Format */
            log_format: string;
            /** Log Level */
            log_level: string;
            /** Max Archive Size */
            max_archive_size: number;
            /** Max Concurrent Archive Builds */
            max_concurrent_archive_builds: number;
            /** Max File Size */
            max_file_size: number;
            /** Max Files Per Package */
            max_files_per_package: number;
            /** Obfuscate Storage Names */
            obfuscate_storage_names: boolean;
            /** Rate Limit Backend */
            rate_limit_backend: string;
            /** Rate Limit Enabled */
            rate_limit_enabled: boolean;
            /** Share Access Token Expire Minutes */
            share_access_token_expire_minutes: number;
            /** Share Verification Code Ttl Minutes */
            share_verification_code_ttl_minutes: number;
            /** Share Verification Max Attempts */
            share_verification_max_attempts: number;
            /** Smtp Timeout */
            smtp_timeout: number;
            /** Smtp Use Tls */
            smtp_use_tls: boolean;
            /** Storage Backend */
            storage_backend: string;
            /** Storage Quota Per User */
            storage_quota_per_user: number;
            /** Storage Quota Total */
            storage_quota_total: number;
        };
        /**
         * ShareAccessRequest
         * @description Email supplied by a recipient to unlock a restricted share.
         */
        ShareAccessRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
        };
        /** ShareCreate */
        ShareCreate: {
            /** Allowed Emails */
            allowed_emails?: string[];
            /** Expires At */
            expires_at?: string | null;
            /** @default public */
            visibility: components["schemas"]["ShareVisibility"];
        };
        /** ShareRead */
        ShareRead: {
            /**
             * Allowed Emails
             * @default []
             */
            allowed_emails: string[];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Expires At */
            expires_at?: string | null;
            /** Id */
            id: number;
            /** Is Enabled */
            is_enabled: boolean;
            /** Package Id */
            package_id: number;
            /** Token */
            token: string;
            visibility: components["schemas"]["ShareVisibility"];
        };
        /** ShareUpdate */
        ShareUpdate: {
            /** Allowed Emails */
            allowed_emails?: string[] | null;
            /** Expires At */
            expires_at?: string | null;
            /** Is Enabled */
            is_enabled?: boolean | null;
            visibility?: components["schemas"]["ShareVisibility"] | null;
        };
        /**
         * ShareVerifyRequest
         * @description Email plus the one-time code emailed to unlock a restricted share.
         */
        ShareVerifyRequest: {
            /** Code */
            code: string;
            /**
             * Email
             * Format: email
             */
            email: string;
        };
        /**
         * ShareVisibility
         * @description Whether a share is open to anyone or limited to specific emails.
         * @enum {string}
         */
        ShareVisibility: "public" | "restricted";
        /**
         * StorageUsage
         * @description The signed-in user's current storage consumption and budget (bytes).
         */
        StorageUsage: {
            /** Storage Quota */
            storage_quota: number;
            /** Storage Used */
            storage_used: number;
        };
        /** Token */
        Token: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /**
         * UploadSessionCreate
         * @description Open a resumable upload: the client declares the file's name and size.
         */
        UploadSessionCreate: {
            /** Content Type */
            content_type?: string | null;
            /** Filename */
            filename: string;
            /** Size */
            size: number;
        };
        /**
         * UploadSessionRead
         * @description State of a resumable upload; ``offset`` is where the client resumes.
         *
         *     When ``complete`` is true the upload finished and ``file`` carries the
         *     created package file. ``chunk_size`` is the size the server suggests the
         *     client send per request.
         */
        UploadSessionRead: {
            /** Chunk Size */
            chunk_size: number;
            /**
             * Complete
             * @default false
             */
            complete: boolean;
            file?: components["schemas"]["PackageFileRead"] | null;
            /** Filename */
            filename: string;
            /** Offset */
            offset: number;
            /** Size */
            size: number;
            /** Upload Id */
            upload_id: string;
        };
        /** UserAdminUpdate */
        UserAdminUpdate: {
            /** Email */
            email?: string | null;
            /** Is Active */
            is_active?: boolean | null;
            /** Is Admin */
            is_admin?: boolean | null;
            /** Storage Quota */
            storage_quota?: number | null;
            /** Username */
            username?: string | null;
        };
        /** UserCreate */
        UserCreate: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /** Username */
            username: string;
        };
        /** UserPage */
        UserPage: {
            /** Items */
            items: components["schemas"]["AdminUserRead"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /** UserRead */
        UserRead: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Id */
            id: number;
            /** Is Active */
            is_active: boolean;
            /** Is Admin */
            is_admin: boolean;
            /** Storage Quota */
            storage_quota: number;
            /** Username */
            username: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_service_settings_api_admin_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceSettingsRead"];
                };
            };
        };
    };
    list_users_api_admin_users_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_all_quotas_api_admin_users_quota_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BulkQuotaUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BulkQuotaResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_user_api_admin_users__user_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_user_api_admin_users__user_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserAdminUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUserRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_user_password_api_admin_users__user_id__password_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordReset"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    all_activity_api_audit_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                action?: string | null;
                actor?: string | null;
                package_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    my_activity_api_audit_mine_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                action?: string | null;
                package_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    auth_config_api_auth_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthConfig"];
                };
            };
        };
    };
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_login_api_auth_login_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Token"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_me_api_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
        };
    };
    change_my_password_api_auth_me_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordChange"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_my_usage_api_auth_me_usage_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StorageUsage"];
                };
            };
        };
    };
    register_api_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_packages_api_packages_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                q?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PackagePage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_package_api_packages_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PackageCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PackageRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_package_api_packages__package_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                package_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PackageRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_package_api_packages__package_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                package_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_package_api_packages__package_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                package_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PackageUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PackageRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_all_files_api_packages__package_id__download_get: {
        parameters: {
            query?: {
                file_ids?: number[] | null;
                token?: string | null;
            };
            header?: never;
            path: {
                package_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_package_download_token_api_packages__package_id__download_token_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                package_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DownloadToken"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_file_api_packages__package_id__files_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                package_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_file_api_packages__package_id__files_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PackageFileRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_all_files_api_packages__package_id__files_delete: {
        parameters: {
            query?: {
                file_ids?: number[] | null;
            };
            header?: never;
            path: {
                package_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_file_api_packages__package_id__files__file_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                file_id: number;
                package_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_owned_file_api_packages__package_id__files__file_id__download_get: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: never;
            path: {
                file_id: number;
                package_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_share_api_packages__package_id__share_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                package_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShareRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    enable_share_api_packages__package_id__share_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                package_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ShareCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShareRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    disable_share_api_packages__package_id__share_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                package_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_share_api_packages__package_id__share_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                package_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ShareUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShareRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_package_stats_api_packages__package_id__stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                package_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PackageStats"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_upload_api_packages__package_id__uploads_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                package_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UploadSessionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadSessionRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_upload_api_packages__package_id__uploads__upload_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                upload_id: string;
                package_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadSessionRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    abort_upload_api_packages__package_id__uploads__upload_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                upload_id: string;
                package_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_chunk_api_packages__package_id__uploads__upload_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                upload_id: string;
                package_id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/offset+octet-stream": string;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadSessionRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ready_api_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    view_share_api_s__token__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicShareRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    access_share_api_s__token__access_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ShareAccessRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicShareRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_shared_archive_api_s__token__download_get: {
        parameters: {
            query?: {
                access?: string | null;
                file_ids?: number[] | null;
            };
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_shared_file_api_s__token__files__file_id__download_get: {
        parameters: {
            query?: {
                access?: string | null;
            };
            header?: never;
            path: {
                token: string;
                file_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_share_api_s__token__verify_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ShareVerifyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicShareRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
